---
- name: Install CA package
  ansible.builtin.package:
    name: ca-certificates
    state: present

- name: Enable custom CA on RHEL 6
  ansible.builtin.command:
    cmd: /usr/bin/update-ca-trust enable
  changed_when: false
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version | int == 6

- name: Copy certificate authorities to system
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ca_certificates_system_path[ansible_os_family] }}"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ lookup('ansible.builtin.fileglob', ca_certificates_source, wantlist=True) }}"
  notify:
    - Update trusted CA (Debian)
    - Update trusted CA (RedHat)
